name: forexample
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_app:
    path: ../forexample_modules/packages/build_app
  home:
    path: ../forexample_modules/packages/home
  login:
    path: ../forexample_modules/packages/login_module

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter_bloc: ^8.0.1
  beamer: ^1.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  freezed_annotation: ^2.0.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/lang/
  fonts:
    - family: ExApp
      fonts:
        - asset: lib/d_system/components/icons/ExApp.ttf
